language: python

python:
  - "2.7"
  - "3.5"

before_install:
    - pip install -U pytest pytest-cov
    - pip install -U coveralls

install:
  - pip install -r requirements_dev.txt

script: py.test tests/tests_pytest --cov-config .coveragerc --cov=plexapi --cov-report=html

after_success:
    - coveralls